joint1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint1
    joint_speed: 4
    motor:
        id: 6
        init: 512
        min: 0
        max: 1023


joint2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint2
    joint_speed: 4
    motor:
        id: 4
        init: 512
        min: 0
        max: 1023